### ISSUE TITLE
Security assesment

### ISSUE THREAD

**Issue by jwz16** [EC528-Fall-2023/Kata-Containers-for-SPARK#13]

**Comment by Vin3ntKing** [comment]
Some of my naive thoughts when I cannot sleep at night:

Since the data flow is:
```
[ External ] <--> [ Yarn/Spark APIs/UIs ] <--> [ Yarn Master ] <--> [ Yarn NodeManager ] <--> [ Container (Regular/Kata) ] <--> [Data Storage ]
```

Then, the potential security tests can be launched at the following points:

```
[ User ] --> [ Yarn Master ] --> [ Yarn NodeManager ] --> [ Container ] --> [ Spark Executor/Driver ] --> [ Data ]
             |                  |                    |                   |
          (Access Control)  (Isolation Test)   (Network Test)       (Resource Test)

```

And for each attack/test, we could think as:

```
[ External Attacker ] --\
                         \
[ Malicious Internal User ] --> [ Yarn/Spark APIs/UIs ]
                         /
[ Compromised Container ] --/
```

**Comment by Vin3ntKing** [comment]
Done with brief documentation in security level comparison between regular container and kata-container and in the context of Yarn + Spark. 

1. [Regular Container vs. Kata Container](https://github.com/EC528-Fall-2023/Kata-Containers-for-SPARK/blob/main/docs/sec_write_up/general_intro.md)
2. [Security Comparison: runc Containers vs. Kata Containers](https://github.com/EC528-Fall-2023/Kata-Containers-for-SPARK/blob/main/docs/sec_write_up/Security_Comparison.md)
3. [Multi-tenancy with Yarn + Spark: runc Containers vs. Kata Containers](https://github.com/EC528-Fall-2023/Kata-Containers-for-SPARK/blob/main/docs/sec_write_up/multi-tenancy_sec_level.md)
