### ISSUE TITLE
I/O Optimization : virtio-fs and SPDK etc... investigate

### ISSUE THREAD

**Issue by sdsz20142087** [EC528-Fall-2023/Kata-Containers-for-SPARK#2]
Optimization about I/O  performance.
1. Virtio-fs:support VM access file system of the host in high performance, avoid swithing between kernal and user space frequently.
https://github.com/virtio-win/kvm-guest-drivers-windows

2. SPDK: handle I/O in user space instead of using stack and heap in the kernal space.
https://github.com/spdk/spdk/tree/master

**write investigation in design doc, including inner logic using graph.**

**Comment by bpkroth** [comment]
As mentioned elsewhere, a document (or Issue here), clearly enumerating the options and tradeoffs of each, what they accomplish and how, and what overheads one might expect (prior to actually measuring it), would be good.
