### ISSUE TITLE
Do research in Benchmark tool and testing case.

### ISSUE THREAD

**Issue by M1schief** [EC528-Fall-2023/Kata-Containers-for-SPARK#27]

**Comment by apavlen** [comment]
please add more details.

**Comment by M1schief** [comment]
Choose use FIO to do IO test. And design 7 testing cases include in testing_plan,md

**Comment by apavlen** [comment]
please elaborate in full sentences

**Comment by M1schief** [comment]
7 testing cased include and detailed explanation is in testing_plan/testing_plan.md
- **Random Read Test**: This test simulates random read operations with a 4KB block size on a 1GB file. It measures the performance of random read access patterns.

- **Random Write Test**: Similar to the random read test, this test focuses on random write operations with a 4KB block size on a 1GB file.

- **Sequential Read Test**: This test measures sequential read performance using a larger 1MB block size on a 1GB file, simulating scenarios like large file transfers.

- **Sequential Write Test**: Similar to the sequential read test, this test assesses sequential write performance with a 1MB block size.

- **Random Read Multi-Threaded Test**: This test introduces concurrency by simulating random read operations with four concurrent threads on a 1GB file.

- **Random Write Multi-Threaded Test**: Similar to the multi-threaded read test, this test focuses on random write operations with four concurrent threads.

- **Mixed Read/Write Test**: This test represents a mixed workload with 70% reads and 30% writes using a 4KB block size on a 1GB file. It's a common scenario in many applications.
