### ISSUE TITLE
Test documentation

### ISSUE THREAD

**Issue by M1schief** [EC528-Fall-2023/Kata-Containers-for-SPARK#28]

**Comment by apavlen** [comment]
is it a test plan? for performance?

**Comment by M1schief** [comment]
It is a plan.
![unnamed](https://github.com/EC528-Fall-2023/Kata-Containers-for-SPARK/assets/59638565/4ad19e89-be28-4d46-9928-fe75214e7c2a)

**Comment by apavlen** [comment]
picture is unreadable.

**Comment by M1schief** [comment]
| Test Scenario         | FIO Parameter Settings                                  | Explanation                                                |
|-----------------------|--------------------------------------------------------|------------------------------------------------------------|
| Random Read Test      | `fio --name=random_read_test --rw=randread --bs=4k --direct=1 --size=512M --numjobs=1 --runtime=30s --filename=/path/to/testfile` | Simulates random read operations with a 4KB block size on a 512MB file for 30 seconds. This test provides a quick assessment of random read performance with reduced data size and runtime. |
| Random Write Test     | `fio --name=random_write_test --rw=randwrite --bs=4k --direct=1 --size=512M --numjobs=1 --runtime=30s --filename=/path/to/testfile` | Similar to the random read test, this test focuses on random write operations with a 4KB block size on a 512MB file for 30 seconds. |
| Sequential Read Test  | `fio --name=sequential_read_test --rw=read --bs=1M --direct=1 --size=512M --numjobs=1 --runtime=30s --filename=/path/to/testfile` | Simulates sequential read operations with a 1MB block size on a 512MB file for 30 seconds. This test evaluates sequential read performance with a larger block size. |
| Sequential Write Test | `fio --name=sequential_write_test --rw=write --bs=1M --direct=1 --size=512M --numjobs=1 --runtime=30s --filename=/path/to/testfile` | Similar to the sequential read test, this test assesses sequential write performance with a 1MB block size on a 512MB file for 30 seconds. |
| Random Read Multi-Threaded Test | `fio --name=random_read_multi_threaded_test --rw=randread --bs=4k --direct=1 --size=512M --numjobs=4 --runtime=30s --filename=/path/to/testfile` | Simulates random read operations with four concurrent threads on a 512MB file for 30 seconds. This multi-threaded test measures the impact of concurrency on random read performance. |
| Random Write Multi-Threaded Test | `fio --name=random_write_multi_threaded_test --rw=randwrite --bs=4k --direct=1 --size=512M --numjobs=4 --runtime=30s --filename=/path/to/testfile` | Similar to the multi-threaded read test, this test focuses on random write operations with four concurrent threads on a 512MB file for 30 seconds. |
| Mixed Read/Write Test | `fio --name=mixed_read_write_test --rw=randrw --rwmixread=70 --bs=4k --direct=1 --size=512M --numjobs=1 --runtime=30s --filename=/path/to/testfile` | Simulates a mixed workload with 70% reads and 30% writes using a 4KB block size on a 512MB file for 30 seconds. This test represents a common mixed I/O scenario with a shorter runtime. |


- **Random Read Test**: This test simulates random read operations with a 4KB block size on a 1GB file. It measures the performance of random read access patterns.

- **Random Write Test**: Similar to the random read test, this test focuses on random write operations with a 4KB block size on a 1GB file.

- **Sequential Read Test**: This test measures sequential read performance using a larger 1MB block size on a 1GB file, simulating scenarios like large file transfers.

- **Sequential Write Test**: Similar to the sequential read test, this test assesses sequential write performance with a 1MB block size.

- **Random Read Multi-Threaded Test**: This test introduces concurrency by simulating random read operations with four concurrent threads on a 1GB file.

- **Random Write Multi-Threaded Test**: Similar to the multi-threaded read test, this test focuses on random write operations with four concurrent threads.

- **Mixed Read/Write Test**: This test represents a mixed workload with 70% reads and 30% writes using a 4KB block size on a 1GB file. It's a common scenario in many applications.
