### ISSUE TITLE
Setting testing tool of FIO for cluster

### ISSUE THREAD

**Issue by M1schief** [EC528-Fall-2023/Kata-Containers-for-SPARK#33]
Set FIO in kata1 and do sample test. The documentation is in testing plan directory testing_plan/sample_result.md.

**Comment by apavlen** [comment]
can you please elaborate?

**Comment by M1schief** [comment]
I am adding a setting up document for FIO and some solutions to error case I met.

**Comment by M1schief** [comment]
## FIO Tool Installation Guide on Debian/Ubuntu Systems

### Installing FIO

To install the FIO tool using `apt`, use the following commands:

```bash
sudo apt-get update
sudo apt-get install fio
```

### Troubleshooting a Specific rsyslog Error

If you encounter the following error:

```
dpkg: error processing package rsyslog (--configure):
```

Follow these steps to resolve it:

1. **Stop the rsyslog service:**

    ```bash
    sudo service rsyslog stop
    sudo systemctl stop rsyslog.service
    ```

2. **Disable rsyslog service (optional):**

    If you don't want `rsyslog` to start during boot:

    ```bash
    sudo systemctl disable rsyslog.service
    ```

3. **Fix broken packages:**

    ```bash
    sudo apt-get -f install
    ```

This will try to correct any broken dependencies on your system.

By following the above steps, you should be able to install the FIO tool and address any `rsyslog` related errors.
```not need
