### ISSUE TITLE
Change README based on the feedback

### ISSUE THREAD

**Issue by jwz16** [EC528-Fall-2023/Kata-Containers-for-SPARK#9]
"The architecture figure shows the architecture of kata containers in spark, but, it doesn’t show what they will need to build in order to perform the analysis.  What are the scripts you will be developing operate against?  How much do you need to automate the deployments? Where will the work be going on?"

**Comment by jwz16** [comment]
We already added the names.

**Comment by jwz16** [comment]
May also need to add a chart to organize dependency between tasks, but need to understand tasks first.

**Comment by jwz16** [comment]
Done.

**Comment by apavlen** [comment]
Please add a link
